#!/bin/bash
# Raspberry Pi Dev Environment Setup Ubuntu 20.04

echo "### Raspberry Pi Dev Environment Setup Ubuntu 20.04 ###"

if [[ -f $HOME/.zshrc ]]; then source $HOME/.zshrc; fi


adduser ceres
usermod -a -G sudo,adm,dialout ceres

apt-get -qq update && apt-get -qq upgrade

apt-get install -qq git zsh mosh neovim tig tmux tldr curl wget htop
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
git clone https://github.com/agkozak/zsh-z $ZSH_CUSTOM/plugins/zsh-z

mkdir -p .zsh
touch .zsh/aliases

ssh-keygen -t rsa -b 4096 -N ''
cat $HOME/.ssh/id_rsa.pub

apt-get --qq install docker.io
usermod -a -G docker ceres

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

if [[ ! -d $HOME/development ]]; then
  echo "create development directory"
  cd $HOME
  mkdir development
fi

cd $HOME/development

echo "Installing Rust"
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

git clone https://github.com/rust-analyzer/rust-analyzer.git && cd rust-analyzer
$HOME/.cargo/bin/cargo xtask install --server
cd .. && rm -rf rust-analyzer


echo "Installing Elixir"
echo "deb https://packages.erlang-solutions.com/debian buster contrib" | tee /etc/apt/sources.list.d/erlang-solutions.list
wget https://packages.erlang-solutions.com/debian/erlang_solutions.asc
apt-key add erlang_solutions.asc
apt update
apt install elixir

cd
zsh
echo "### Setup Complete!! ###"
