#!/bin/bash
# Raspberry Pi Dev Environment Setup Ubuntu 20.04

echo "### Raspberry Pi Dev Environment Setup Ubuntu 20.04 ###"

if [[ -f $HOME/.zshrc ]]; then source $HOME/.zshrc; fi


adduser ceres
usermod -a -G sudo,adm,dialout ceres

apt-get -qq update && apt-get -qq upgrade

apt-get install -qq git zsh mosh neovim tig tmux tldr curl wget htop

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
git clone https://github.com/agkozak/zsh-z $ZSH_CUSTOM/plugins/zsh-z

mkdir -p .zsh
touch .zsh/aliases

ssh-keygen -t rsa -b 4096 -N ''
cat $HOME/.ssh/id_rsa.pub

if [[ ! -d $HOME/downloads ]]; then
  echo "create downloads directory"
  cd $HOME
  mkdir downloads
fi

cd $HOME
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

zsh

cd downloads
git clone https://github.com/AyashiNoCeres/my_config.git && cd my_config

cp .zshrc ~/
cp .zshenv ~/
cp .tmux.conf ~/
cp .tigrc ~/
cp .zsh/aliases ~/.aliases
cp kali.zsh-theme ~/.oh-my-zsh/custom/themes

echo "### Setup Complete!! ###"
