#!/bin/bash
# WSL Environment Setup Ubuntu 20.04

echo "### WSL dev Environment Setup Ubuntu 20.04 ###"

if [[ -f $HOME/.zshrc ]]; then source $HOME/.zshrc; fi

apt-get -qq update && apt-get -qq upgrade

apt-get install -qq git zsh mosh neovim tig tmux tldr curl wget htop
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
git clone https://github.com/agkozak/zsh-z ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/.oh-my-zsh/plugins/zsh-z

ssh-keygen -t rsa -b 4096 -N ''
cat $HOME/.ssh/id_rsa.pub

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

if [[ ! -d $HOME/development ]]; then
  echo "create development directory"
  cd $HOME
  mkdir development
fi

mkdir development_tools
cd $HOME/development_tools

echo "Installing Rust"
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

git clone https://github.com/rust-analyzer/rust-analyzer.git && cd rust-analyzer
$HOME/.cargo/bin/cargo xtask install --server
cd .. && rm -rf rust-analyzer

cd
zsh
echo "### Setup Complete!! ###"
